#! /usr/bin/bash

find Patro -name "flycheck*.py" -exec rm {} \;
find Patro -name "parsetab.py" -exec rm {} \;

api=doc/sphinx/source/api
rm -rf ${api}

echo
echo Generate RST API files
pyterate-rst-api Patro

echo
echo Run Sphinx
pushd doc/sphinx/
./make-html #--clean
popd
