#! /bin/bash

pushd output

pdftoppm pattern-a0.pdf out
convert -resize x1000 out-1.ppm pattern-a0.png

pdftoppm -f 4 -l 4 pattern-a4.pdf out
convert -resize x1000 out-04.ppm pattern-a4.png

rm out*.ppm

